[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = true
fileWatcherType = "auto"
runOnSave = true

[theme]
primaryColor = "#00e5b0"
backgroundColor = "#000000"
secondaryBackgroundColor = "#060909"
textColor = "#E6F6F3"
font = "Inter"

[client]
showErrorDetails = true

[runner]
fastReruns = true
magicEnabled = true
